version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: recettesCuisine_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123Espelette
      MYSQL_DATABASE: recettescuisine_db
      MYSQL_USER: Gimli
      MYSQL_PASSWORD: Psychokiller75.
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
